### ISSUE TITLE
Can't get started

### ISSUE THREAD

**Issue by MystBunny** [punk7890/Star-Fox-64-Randomizer#1]
It appears I don't have the correct version, so I went looking for 1.0, and I found a few downloads, but all I can get is "Rom could not be recognized" on the toolkit for all of them.

**Comment by GB-CG** [comment]
Maybe it's byteswapped? You can change it to Big Endian with this [tool](https://www.zophar.net/utilities/n64aud/tool-n64.html).

**Comment by MystBunny** [comment]
No luck. I can't get the tool to recognize or open any of the roms at all. Tried unzipping them, leaving them zipped, dragging them to the exe. The ones I could find have .n64 extension. Should they be another?

**Comment by punk7890** [comment]
You can also try this online tool to byteswap your ROM: https://hack64.net/tools/swapper.php

The problem you're having is because it's either not 1.0, or it's 1.0 but in Little Endian byte order. Sadly, the decompression tool only supports Big Endian. If you open the ROM in a hex editor and see "STARFOX64" at 0x20, then it's in Big Endian. If it isn't, you'll see "TSRAOF6X 4".

.n64 extensions are generally in Little Endian byte order.

**Comment by MystBunny** [comment]
Thank you so much, that did it! Gonna do a blind run on Youtube tonight. Just one last question. What is marathon mode?

**Comment by punk7890** [comment]
It runs you through all of the levels in the game in order of blue path, yellow path then red path. At the end of the yellow path, you will be sent to training mode as an extra level.

I've been meaning to make a section in the readme about these options soon.

**Comment by MystBunny** [comment]
Okay cool, I'll keep an eye out. And thanks bunches for the help. Just finished my playthrough with random dialog and that shit is some WACKY fun! I got reminded by ALL my wingmen how daddy screamed before he died >.>

**Comment by GB-CG** [comment]
> No luck. I can't get the tool to recognize or open any of the roms at all.

I don't understand why the offline tool doesn't work but the web version does. Never had an issue with tool64.

**Comment by MystBunny** [comment]
I hope it's okay if I link the first half of my playthrough here?
https://www.youtube.com/watch?v=8KqSUDegxGA
