### ISSUE TITLE
Corneria Boss Rush Quick Score Crash

### ISSUE THREAD

**Issue by MobiusNero** [punk7890/Star-Fox-64-Randomizer#10]
Hello! First of all, thanks a lot for this randomizer, I absolutely love it!

The issue happens when playing against Corneria's Easy Route Boss (Granga's Mech) while using Boss Rush AND Quick Score Screens.
It happened first in a random planet playthrough, and then I got to recreate the issue several times using the Select Planet option. 

After beating the boss, the Quick Score screen does not show up, the game plays the entire post-boss cutscene as if playing the vanilla game. After the regular score screen, the Arwings gets stuck in the position right before the crew departs to the next planet (see image attached). The audio plays regularly, the music loops but the ships don't move, so the cutscene doesn't end.

Playing in Boss Rush without Quick Score does not cause the issue.
Playing without Boss Rush with Quick Score does not cause the issue either.

I couldn't check if this happens with the Hard Route's Boss (Attack Carrier). Everytime I've played in Boss Rush, the game always put me against Granga's Mech.

Once again, thanks for the randomizer!

![Star Fox Crash](https://github.com/user-attachments/assets/407f9557-ec45-4b06-b2c6-6c7d19820568)

**Comment by punk7890** [comment]
Thanks for the bug report. Should be fixed in latest release.
