### ISSUE TITLE
Soft Lock - Sector X Expert

### ISSUE THREAD

**Issue by GenichiroOokami** [punk7890/Star-Fox-64-Randomizer#4]
There appears to be an issue where taking the warp in Sector X in expert will cause a soft lock. Soft lock has occurred in two playthroughs back to back.
Version: Beta-45-Hot-Fix 
OS: Windows 10 64bit
Emulator: BizHawk, Mupen64Plus core

**Comment by punk7890** [comment]
Should be fixed now in latest release.
