### ISSUE TITLE
Choose planets, but go to boss directly

### ISSUE THREAD

**Issue by MorKsQC** [punk7890/Star-Fox-64-Randomizer#6]
Hi there!

I was wondering if you were able to add a mode (or a toggle on the Choose Planets mode) where instead of starting a planet at its beginning, it would start at its boss, making it so that I can fight any boss at any given time.

I tried coding it myself on my fork, but trying to ARMIPS.exe with your Compile.asm was proven to be unsuccessful, as I had multiples errors regarding .d32 and other variables referenced in your files.

Let me know if you'd be willing to work together or help my situation. Thank you!

**Comment by punk7890** [comment]
You can combine Choose Planets and Boss Rush Mode for a similar effect, the only difference here is Boss Rush Mode needs to be on as well.

That's strange about your compiling problems as copying this repository locally with the same file structure should work fine. Granted, I believe I haven't updated ARMIPS in a year or so, so it might be something odd with the new versions (if there is any). Happy to help if there is still issues.

**Comment by MorKsQC** [comment]
Thanks for replying!

Unfortunately, enabling Boss Rush Mode and Choose Planets together does not work. I can choose a planet, but whichever one I choose, it will always bring me back to Corneria Boss instead of the boss of the selected planet

**Comment by punk7890** [comment]
Oversight on my part. Should be fixed in latest release.

**Comment by MorKsQC** [comment]
Thanks!
